[server]
host = "0.0.0.0"
port = 8484

[downloads]
directory = "/tmp/flasharr-downloads"
max_concurrent = 3
segments_per_download = 4

[fshare]
email = ""
password = ""

[sonarr]
enabled = true
url = "http://192.168.1.110:8989"
api_key = "6cc69aeeec80439eadc8ec63ef63f839"
auto_import = true

[radarr]
enabled = true
url = "http://localhost:7878"
api_key = "test-radarr-key"
auto_import = false

[indexer]
enabled = true
api_key = "flasharr-default-key"
